statics !!!!!! expect it doesn't work :-(
error[E0493]: destructor of `TargetOptions` cannot be evaluated at compile-time
  --> compiler/rustc_target/src/spec/targets/nvptx64_nvidia_cuda.rs:50:15
   |
50 |             ..TargetOptions::default()
   |               ^^^^^^^^^^^^^^^^^^^^^^^^ the destructor for this type cannot be evaluated in statics
...
53 | };
   | - value is dropped here

error[E0015]: cannot call non-const operator in statics
    --> compiler/rustc_target/src/spec/targets/x86_64_unknown_none.rs:26:31
     |
26   |         supported_sanitizers: SanitizerSet::KCFI | SanitizerSet::KERNELADDRESS,
     |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
note: impl defined here, but it is not `const`
    --> /home/archie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitflags-2.4.2/src/public.rs:359:9
     |
317  |   macro_rules! __impl_public_bitflags_ops {
     |   --------------------------------------- in this expansion of `$crate::__impl_public_bitflags_ops!` (#2)
...
359  |           impl $crate::__private::core::ops::BitOr for $PublicBitFlags {
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
    ::: /home/archie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitflags-2.4.2/src/lib.rs:446:1
     |
446  |   macro_rules! bitflags {
     |   --------------------- in this expansion of `bitflags::bitflags!` (#1)
...
571  | /             $crate::__impl_public_bitflags_ops! {
572  | |                 $BitFlags
573  | |             }
     | |_____________- in this macro invocation (#2)
     |
    ::: compiler/rustc_target/src/spec/mod.rs:1220:1
     |
1220 | / bitflags::bitflags! {
1221 | |     impl SanitizerSet: u16 {
1222 | |         const ADDRESS = 1 << 0;
1223 | |         const LEAK    = 1 << 1;
...    |
1234 | |     }
1235 | | }
     | |_- in this macro invocation (#1)
     = note: calls in statics are limited to constant functions, tuple structs and tuple variants
     = help: add `#![feature(const_trait_impl)]` to the crate attributes to enable
     = note: consider wrapping this expression in `Lazy::new(|| ...)` from the `once_cell` crate: https://crates.io/crates/once_cell